tamasfe/aide

crates/aide/src/axum/routing.rs

`aide::axum::routing::get` generates a schema for the request, but does not generate a schema for the response.
So, I add the response schema in case of success.

Add: default response.

---

crates/aide/Cargo.toml
crates/aide/src/axum/inputs.rs
crates/aide/src/gen.rs
crates/aide/src/lib.rs
crates/aide/src/redoc/mod.rs

Add a small wrapper to embed redoc in axum app. 
I originally planned to add swagger-ui but it seems openapi 3.1 is not supported there yet.

feat(axum): add axum redoc ui wrapper

---

crates/aide/Cargo.toml
crates/aide/src/axum/mod.rs
crates/axum-jsonschema/Cargo.toml
examples/example-axum/src/docs.rs
examples/example-axum/src/main.rs
examples/example-axum/src/todos/routes.rs

BREAKING CHANGE: Require using `nest_api_service` instead of `nest_service` or `nest` to propagate the API documentation. Also propagate changes to `with_state` from axum 0.6.0-rc.5.
Latest axum release candidate introduced some breaking changes. Since 0.6.0 is around the corner I have marked this version of aide as a release candidate too. I personally just wanted to be able to follow with the release candidates in my project.

feat(aide): Update to axum 0.6.0-rc.5

---

crates/aide/src/axum/outputs.rs
crates/aide/src/gen.rs

It would be meaningful for the API Client to output error responses (Status, ResponseBody) to OpenAPI for error handling.
As a simple example, I would implement OperationOutput to "JsonRejection".
But maybe I should work on the axum side instead of the aide.
It would be better to ask JsonRejection itself to tell what error codes it can return.
In that case, the modification of [composite_rejection!](https://github.com/tokio-rs/axum/blob/e0ef641e5fc12048b1632cf2feebddac19a2f8ad/axum/src/extract/rejection.rs#L123).
What do you think of this idea?

Suggestion: impl OperationOutput for Rejections.

---

crates/aide/Cargo.toml
crates/aide/src/axum/mod.rs
crates/aide/src/axum/routing.rs

I have noticed some differences between aide's `ApiMethodRouter` and axum's `MethodRouter` which made composing services from several routers (created in different scopes) frustrating. AFAIK the changes I have made are all additive and non-breaking.  This is related to axum 0.6 release which made routers carry state in their types.

Match more closely axum's API for MethodRouter

---

crates/aide/Cargo.toml

I was having troubles with the generated OpenAPI spec not passing validation (using [this tool](https://github.com/p1c2u/openapi-spec-validator)), specifically due to the `parameters.style` field being present where it's apparently not expected (in a header parameter). 
After looking through the code I found that [it is possible to disable default value serialization](https://github.com/tamasfe/aide/blob/master/crates/aide/src/openapi/parameter.rs#L174), however it is locked behind a feature that is impossible to enable since it isn't specified in `Cargo.toml`.
This PR simply defines the feature in `Cargo.toml` so that users can enable it.

feat(aide): add skip_serializing_defaults feature

---

crates/axum-jsonschema/Cargo.toml
crates/axum-jsonschema/src/lib.rs

Does what it says on the tin :) Closes #17
Some notes:
- jsonschema have made their types `OutputUnit` and `JSONPointer` impossible to use elsewhere and so I have had to make a copy. With this, the objects have `snake_case` keys rather than `camelCase`
- I have made sure to copy the styling from jsonschema for the serde error path so that they are similar
- I have exposed a 'type' parameter on the error for computers to better understand
- I have made sure to have at least an 'error' string on all errors for convenience
- despite `serde_path_to_error` returning a single value, I have made `serde_error` also a vec for consistency
- I pulled in itertools for convenience.  This can be replaced.
```rust
// the input to our `create_user` handler
#[derive(Deserialize, JsonSchema)]
pub struct …
```

feat: expose serde errors with same format as jsonschema validation

---

crates/aide/src/impls/mod.rs

Axum allows to have routes returning arbitrary-arity tuples, as long as the elements implement the correct trait. This PR adds more blanket implementations of OperationOutput so that old Axum routes can compile when migrated to Aide routes.
Ref: https://docs.rs/axum/0.6.4/axum/response/index.html (0.6.4 is `latest` at the time of commit)
Closes #30

Add more blanket tuple impls of OperationOutput

---

crates/aide/src/axum/outputs.rs

Allow endpoints that are `Redirect` to be used in API documentation; my use case for it is to have spec for the OpenIDConnect / OAuth endpoints that are based on redirects

fix(aide): add support for Redirect axum response

---

crates/aide/src/transform.rs

Fix typo in `aide::transform::TransformOperation::response_range()` method.

fix(aide): fix typo in response_range() method

---

crates/aide/src/axum/mod.rs

This PR adds a transformation method to ApiRouter, allowing to transform the contained PathItems.
This, amongst other things, allows adding parameters manually in places where aide is unable to infer the parameters existance, such as when they are added through nest-calls via middleware.

Add with_path_items method to ApiRouter (fixes #46)

---

examples/example-axum/src/todos/routes.rs

Fix response code in the example.
Note: with https://github.com/hyperium/http/pull/591, `http::StatusCode::as_u16()` will be directly usable for the generic parameter.

fix(example-axum): fix response code typo in the example

---

crates/aide/src/axum/routing.rs

While looking for a fix for #51 I realized that the more appropriate fix in my situation is to merge on the `MethodRouter` level. However, this is missing on aide's `ApiMethodRouter` currently so this PR adds that.

Implement `merge` on `ApiMethodRouter`

---

crates/aide/Cargo.toml
crates/aide/src/axum/outputs.rs

- updated axum-extra to 0.7.3
- added OperationOutput to cookie jar so it can be modified properly, as changes must be returned from the response.

updated axum-extra and added output for cookie jars

---

crates/aide/Cargo.toml

Should be quite straightforward - current version of `jwt-authorizer` is 0.9

Pull up jwt-authorizer to 0.9

---

crates/aide/Cargo.toml
crates/aide/src/redoc/mod.rs

It would normally be set by the project containing aide as a dependency with axum-sqlx-tx, but in the docs build it wasn't set. So eventually the 'sqlx-rt' crate complained that it missed a feature.
Also fixing calling `cargo test --all` by adding a generic parameter to `ApiRouter::new()` call.

Fix docsrs build

---

crates/aide/src/axum/mod.rs
crates/aide/src/openapi/openapi.rs
crates/aide/src/transform.rs

- Solves #69 
- Fixes for compiler and clippy warnings
- Changed `openapi` field type from `'&static str` to `Cow<'static, str>` for the relaxing requirement for deserialized data (actual for the case when you trying to deserialize data which not previously statically included in your binary)

Fix openapi deserialize

---

crates/aide/Cargo.toml

Starting with `jwt-authorizer 0.10` one has a choice of TLS implementation to use with it. 
The `default-features = false` is set here to not affect the end user selection of which TLS implementation to use.

Pull up jwt-authorizer to 0.10

---

crates/aide-axum-sqlx-tx/Cargo.toml
crates/aide-axum-sqlx-tx/src/lib.rs

- implemented drop in replacement axum-sqlx-tx in a separate crate using new `NoApi` struct
- aded feature flags for selecting relevant version and features
- sqlite was left out due to conflicts.

feat(crate): aide-axum-sqlx-tx

---

Cargo.toml
crates/aide-axum-sqlx-tx/Cargo.toml
crates/aide/Cargo.toml
crates/aide/src/axum/inputs.rs
crates/aide/src/axum/mod.rs
crates/aide/src/axum/routing.rs
crates/aide/src/gen.rs
crates/aide/src/helpers/no_api.rs
crates/aide/src/helpers/use_api.rs
crates/aide/src/helpers/with_api.rs
crates/aide/src/redoc/mod.rs
crates/axum-jsonschema/Cargo.toml
crates/axum-jsonschema/src/lib.rs
examples/example-axum/Cargo.toml
examples/example-axum/src/main.rs

Closes #87, closes #82.
I also fixed the inconsistencies between the router's `<op>` and `<op>_with` functions so that the former only calls the latter with a no-op closure, thus they cannot get out of sync.
I also changed the document generation defaults:
- Responses are now inferred by default, as this seems to be the most common use-case, and the route functions will respect the global setting (this was a bug before).
- Schema inlining is disabled by default, because schema collisions are fixed in https://github.com/GREsau/schemars/pull/247.

Axum 0.7 support

---

crates/aide/src/gen.rs

Closes #95
I just realized it does the same thing as #94, yet this PR avoids duplicate code like in #94

Fix inconsistency in extracting schema and cause redoc to crash

---

crates/aide/Cargo.toml

jwt-authorizer 0.13 is incompatible with the current aide due to its dependence on axum 0.6

Updated jwt-authorizer dependency version

---

crates/aide/Cargo.toml
crates/aide/src/helpers/no_api.rs
crates/aide/src/helpers/use_api.rs
crates/aide/src/helpers/with_api.rs

Do you want me to try `macro_rules!` "derives" as an alternative? I think due to all the types here being generic, that would probably only save a few lines and the macro code would be a tad hard to read, so I'd personally prefer this for readability. It's not that much boilerplate IMHO.
Resolves #122.

Replace derive_more derives with manual implementations

---

.github/workflows/typos.yml
.typos.toml
crates/aide/src/axum/mod.rs
crates/aide/src/gen.rs
crates/aide/src/helpers/with_api.rs
crates/axum-jsonschema/src/lib.rs

With the help of https://github.com/crate-ci/typos

Fix a handful of typos and check for new ones in CI

---

crates/aide/src/axum/mod.rs

Allow adding handlers to `ApiMethodRouter` that have a layer applied via `Handler::layer`.

Implement OperationHandler for axum::handler::Layered

---

crates/aide/src/axum/mod.rs
crates/aide/src/transform.rs

This aligns the signature of `impl Service for ApiRouter` to be the same as `impl Service for axum::Router`

Make the Service impl for ApiRouter generic

---

crates/aide/src/openapi/security_scheme.rs

It causes issues with scalar making auth unusable if bearer_format is set to `None`.

security_scheme: http, bearer_format should be string or omitted

---

crates/aide/CHANGELOG.md
crates/aide/Cargo.toml

I would like to release v0.13.5. [`cargo semver-checks`](https://github.com/obi1kenobi/cargo-semver-checks) reports no breakage since the last release.
I'd run `cargo publish` locally after this is merged if that's fine with you.
Please don't merge this PR on my behalf, I prefer merging myself once approved on repos where I have write access.

Release v0.13.5

---

crates/aide-macros/Cargo.toml
crates/axum-jsonschema/Cargo.toml
examples/example-axum-worker/Cargo.toml
examples/example-axum/Cargo.toml

… and collapse some lines in `Cargo.toml`s.

Remove unused dependencies

---

crates/aide/src/axum/mod.rs

This is a first test implementation to resolve #138. It doesn't include tests and is meant as a starting point for discussions.

Add *_with_tsr implementations to axum::ApiRouter.

---

crates/aide/src/axum/mod.rs

The extra `%` was piping the values through [`tracing::field::display`](https://docs.rs/tracing/latest/tracing/field/fn.display.html), which makes little sense for `&str`s, and would lead to quotes being omitted in places where they would be helpful (for example `tracing_subscriber`s `fmt::Subscriber`).

Don't go through Display for &str tracing fields

---

crates/aide-axum-sqlx-tx/Cargo.toml
crates/aide-axum-typed-multipart/Cargo.toml
crates/aide-axum-typed-multipart/src/lib.rs
crates/aide/Cargo.toml
crates/aide/src/axum/inputs.rs
crates/aide/src/axum/mod.rs
crates/aide/src/axum/routing.rs
crates/aide/src/helpers/no_api.rs
crates/aide/src/helpers/use_api.rs
crates/aide/src/helpers/with_api.rs
crates/axum-jsonschema/Cargo.toml
crates/axum-jsonschema/src/lib.rs
examples/example-axum-worker/Cargo.toml
examples/example-axum-worker/src/todos/routes.rs
examples/example-axum/Cargo.toml
examples/example-axum/src/todos/routes.rs

fixes #167
Based on this [announcement](https://tokio.rs/blog/2025-01-01-announcing-axum-0-8-0)

feat: axum v0.8 support

---

crates/aide/src/axum/mod.rs
crates/aide/src/util.rs

Hi!
This PR attempts to fix https://github.com/tamasfe/aide/issues/134.
Currently, API documentation for nested routes is built by combining the path of the base route (with trailing slashes removed) with the path of the nested route.
If a path of a nested route is only "/", as seen in the todo list example, this leads to that path now containing a trailing slash:
```rust
ApiRouter::new().nest_api_service("/todo", ApiRouter::new().api_route("/",post_with(handler, docs)))
```
Generates this path:
```json
"paths": {
"/todo/": {
...
},
...
}
```
This PR fixes this issue by removing any trailing slahes after the nested path is built in the `nest` and `nest_api_service` functions.
One edge case needs to be handled. In a construct like the following:
```rust …
```

fix: remove trailing / from nested paths

---

crates/aide-macros/Cargo.toml
crates/aide/CHANGELOG.md
crates/aide/Cargo.toml

… and use an exact version requirement for aide-macros dependency.
In case we add new things to the macros crate that depend on new
functionality from the main crate, it's important that the macro crate
is not upgraded in a downstream project without the main crate being
updated.

Release v0.14.1

---

crates/aide/src/axum/outputs.rs

`subschema_for` is likely to return just a reference to a schema, and it will not contain any metadata. However, `axum::Json` (and `axum::Form`) do not try to resolve the reference before extracting schema description, and that leaves blank response descriptions in rendered docs. So I added a call to `resolve_schema` to ensure that we get the actual schema before extracting its description.

fix(aide-axum): properly infer response descriptions

---

crates/aide/Cargo.toml
crates/aide/src/impls/mod.rs
crates/aide/src/impls/serde_qs.rs

serde_qs is released with axum v0.8 support. Let's bring it back to aide.
Additionally implement `OperationInput` for `OptionalQsQuery`, see https://github.com/samscott89/serde_qs/pull/102

Bring back serde_qs, bump to v0.14

---

crates/aide/src/axum/mod.rs

It used to overwrite all routes in the given OpenApi object, rather than merging the definitions from self into it as described in documentation.

Make finish_api work as described

---

crates/aide/src/axum/routing/typed.rs

- for https://github.com/tamasfe/aide/issues/231

feat(axum): typed routing *_with

---

crates/aide/src/axum/inputs.rs

The impl was removed in the axum 0.8 upgrade due to the type moving to axum-extra.

Add axum_extra::extract::Host support
